### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by arouinfar** [phetsims/build-a-fraction#7]
As pointed out in https://github.com/phetsims/QA/issues/267, this sim needs screenshots for 1.0.

**Comment by amanda-phet** [comment]
@phet-steele the main screenshot should match the current sim's screenshot.

**Comment by phet-steele** [comment]
Commited. Main followed by alts:

![build-a-fraction-screenshot](https://user-images.githubusercontent.com/5863899/51766654-58e48580-2098-11e9-9dab-cdb052f06161.png)

![build-a-fraction-screenshot-alt1](https://user-images.githubusercontent.com/5863899/51766657-5b46df80-2098-11e9-86df-1fea39fa9921.png)

![build-a-fraction-screenshot-alt2](https://user-images.githubusercontent.com/5863899/51766660-5b46df80-2098-11e9-9e9f-2faf9445492c.png)

![build-a-fraction-screenshot-alt3](https://user-images.githubusercontent.com/5863899/51766661-5bdf7600-2098-11e9-9746-f5483d58d6fe.png)

**Comment by amanda-phet** [comment]
Looks good to me! We probably don't need that many completed challenges shown though.. don't we have a rule about not giving away answers?

**Comment by phet-steele** [comment]
> We probably don't need that many completed challenges shown though.. don't we have a rule about not giving away answers?

Well for the main screenshot, I was instructed to copy the existing java version screenshot. That's why the main has all those answers.

For the others, I guess I figured we are already breaking the rule in the main screenshot, so what should it bother to keep that up? I could maybe see changing the level 8 one to have fewer answers. @amanda-phet is there anything you want done specifically?

**Comment by phet-steele** [comment]
Done.
